institution: 'Norwegian Meteorological Institute (METNO)'
creator_role: 'Data center contact'
creator_name: 'NBS Helpdesk'
creator_email: 'nbs-helpdesk@met.no'
creator_url: 'https://met.no'
creator_institution: 'Norwegian Meteorological Institute'
contributor_role: 'Metadata author'
contributor_name: 'NBS Helpdesk'
contributor_email: 'nbs-helpdesk@met.no'
contributor_url: 'https://met.no'
contributor_institution: 'Norwegian Meteorological Institute'
publisher_name: 'NBS Helpdesk'
publisher_email: 'nbs-helpdesk@met.no'
publisher_organisation: 'Norwegian Meteorological Institute'
publisher_url: 'https://met.no'
metadata_status: 'Active'
dataset_language: 'en'
dataset_production_status: 'In Work'
processing_level: 'Operational'
access_constraint: 'Open'
license_text: 'The use of these data are covered by the Legal notice on the use of Copernicus Sentinel Data and Service Information at https://sentinels.copernicus.eu/documents/247904/690755/Sentinel_Data_Legal_Notice'
license: 'https://sentinels.copernicus.eu/documents/247904/690755/Sentinel_Data_Legal_Notice (Sentinel_Data_Legal_Notice)'
project: 'Nasjonalt BakkeSegment'
project_short_name: 'NBS'
collection: 'NBS'
naming_authority: 'no.met'
spatial_representation: 'grid'
source: 'Space Borne Instrument'
geospatial_bounds_crs: 'EPSG:4326'


